version: '3'

services:
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    container_name: 'redis-db'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - ./redis_dump:/bitnami/redis/data
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb

  mysql:
    image: mysql:5.7
    container_name: 'mysql-db'
    restart: always
    environment:
      MYSQL_DATABASE: tadp
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: dryan
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:4.2.10-bionic
    container_name: 'mongo-db'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

volumes:
  mysql_data:
    driver: local
