version: '2.1'

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:2.1.4
    container_name: kong-migration
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations bootstrap

  kong:
    image: kong:2.1.4
    container_name: kong
    restart: always
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
  
#   konga:
#     image: pantsel/konga
#     environment:
#       - TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
#       - DB_ADAPTER=postgres
#       - DB_HOST=kong-database
#       - DB_PORT=5432
#       - DB_DATABASE=db_konga
#       - DB_USER=kongauser
#       - DB_PASSWORD=kongapassword
#       - NODE_ENV=development
#       - KONGA_HOOK_TIMEOUT=10000
#     restart: on-failure
#     ports:
#     - 9000:1337
#     depends_on:
#         kong-database:
#             condition: service_healthy

# Refer: https://github.com/peter-evans/docker-compose-healthcheck